### ISSUE TITLE
感觉可以学习下faygo的参数自动绑定验证的特性

### ISSUE THREAD

**Issue by arden** [johng-cn/gf#11]
看了一下gf感觉很不错，但有一点我觉得可以学习下faygo的参数自动绑定验证的功能，方便快捷，一个struct hander非常方便。。。

**Comment by johng-cn** [comment]
感谢提供建议，我后续会参考一下。

**Comment by johng-cn** [comment]
你好，faygo那样的设计确实很方便，但是耦合度很高，其他的框架在这块设计的时候耦合度都很高。
gf在这块设计的时候，按照功能的内聚封装，参数自动绑定和验证分成了两个模块实现，这样耦合性很低，长远维护来讲成本更低。
1. 参数自动绑定：请求参数可自动绑定到对象上，没有自动校验功能，请参考：http://gf.johng.cn/702771#3struct_68
2. 参数绑定校验：根据对象的特定标签定义进行参数校验，请参考：http://gf.johng.cn/702784#2struct_tag_200
