### ISSUE TITLE
gfsnotify在win10下无效？

### ISSUE THREAD

**Issue by linuxlibs** [johng-cn/gf#12]
```
package main

import (	
    "fmt"
    "gitee.com/johng/gf/g/os/gfsnotify"
)

func main() {

    err := gfsnotify.Add("C:/", func(event *gfsnotify.Event) {
        if event.IsCreate() {
            fmt.Println("创建文件 : ", event.Path)
        }
        if event.IsWrite() {
            fmt.Println("写入文件 : ", event.Path)
        }
        if event.IsRemove() {
            fmt.Println("删除文件 : ", event.Path)
        }
        if event.IsRename() {
            fmt.Println("重命名文件 : ", event.Path)
        }
        if event.IsChmod() {
            fmt.Println("修改权限 : ", event.Path)
        }
    })
    if err != nil {
        fmt.Println("遇到错误")
    } else {
        select {}
    }
}

```

以上代码基于[官网文档](http://gf.johng.cn/593848)修改的，把打印直接显示到屏幕上。但是运行后，没有任何显示。换其他目录操作，也一样。

**Comment by johng-cn** [comment]
只支持文件监控

**Comment by linuxlibs** [comment]
可以考虑用更实用的 https://github.com/andreaskoch/go-fswatch 来替代 https://github.com/fsnotify/fsnotify/ 作为底层监控库

**Comment by johng-cn** [comment]
@linuxlibs 我看了下你发的go-fawatch的包的实现，没有用到底层的inotify系统调用，对于目录的监控是采用定期遍历查询的方式来实现监控。这种方式其实之前我也实现过，但是一旦监控的文件量一旦上来之后效率就会急剧下降，类似于socket通信中的SELECT和EPOLL的区别。此外，我粗略看了一下它的实现源码，在并发安全这块可能需要注意一下是否有问题。

**Comment by johng-cn** [comment]
@linuxlibs 其实依靠```gfsnotify```现有的机制很容易实现对于目录的监控，我把这块需求加到TODO里面去，也欢迎你贡献代码。

**Comment by linuxlibs** [comment]
我之前借助 github.com 上现其他开发者基于inotify的跨平台项目，已经实现了支持目录和文件的监控。可以合并到gf。

**Comment by johng-cn** [comment]
@linuxlibs 欢迎提PR，非常欢迎贡献代码

**Comment by linuxlibs** [comment]
大体看了现有的一些开源项目，确实没有直接可用的自动递归检测修改的拿来可用。最好的办法还是你说的“其实依靠gfsnotify现有的机制很容易实现对于目录的监控”。

**Comment by johng-cn** [comment]
@linuxlibs ```gfsnotify```增加了目录递归监控的特性，可以方便地添加对目录及其下所有子级的监控。
