### ISSUE TITLE
请问是否计划集成swagger文档功能？

### ISSUE THREAD

**Issue by forging2012** [johng-cn/gf#13]
请问是否计划集成swagger文档功能？
beego、faygo等框架都很好的内嵌集成了swagger文档功能。

**Comment by johng-cn** [comment]
@forging2012 你好，其实`GF`很容易生成接口文档，也可以读取接口对应的程序文件/方法注释生成对应的接口说明，只不过目前`GF`正准备国际化，有一些事情需要处理，这块的优先级放到了后面。如果能够提PR贡献代码就再欢迎不过了。

**Comment by zhwei820** [comment]
@johngcn  的确很简单, swago提供了swagger注释分析功能, 可以很方便地生成swagger文件, 再利用http handler暴露出来即可. 
demo1: https://github.com/zhwei820/gogf-swagger
demo2: https://github.com/zhwei820/gf-demos
下面是效果:
![testSelection_023](https://user-images.githubusercontent.com/4001744/61889975-1281bd80-af39-11e9-9cf9-e4938a662dfc.png)

**Comment by johngcn** [comment]
@zhwei820 做得不错，希望继续努力，我fork了一份仓库到gogf下：https://github.com/gogf/gf-swagger

**Comment by zhwei820** [comment]
> @zhwei820 做得不错，希望继续努力，我fork了一份仓库到gogf下：https://github.com/gogf/gf-swagger

向前辈学习.

**Comment by ttcc** [comment]
@zhwei820 请问 slice 的 example 应该如何写呀 ? 谢谢
![image](https://user-images.githubusercontent.com/64948533/81400475-c74f3900-915f-11ea-94b4-dbeebe91d2fa.png)
