### ISSUE TITLE
输出不了json

### ISSUE THREAD

**Issue by alonCn** [johng-cn/gf#14]
`type DemoInfo struct {
		Name 	string
		Age	string
	}

	l := map[interface{}][]DemoInfo{}

	el := [...]DemoInfo{
		{Name:"Bala", Age:"15"},
		{Name:"CeCe", Age:"18"},
		{Name:"ChenLo", Age:"28"},
		{Name:"Bii", Age:"22"},
		{Name:"Ann", Age:"23"},
		{Name:"Bmx", Age:"88"},
	}
	fmt.Println(el)

	for _,v := range el{
		l[string(v.Name[0])] = append(l[string(v.Name[0])],v)
	}
	fmt.Println(l)

	c.Response.WriteJson(l)`

**Comment by johng-cn** [comment]
该问题是标准库的`json`包不支持`map[interface{}]interface{}`类型，`GF`框架已做了处理，更新框架代码到最新版本即可解决。
