### ISSUE TITLE
事务操作只支持一条语句？

### ISSUE THREAD

**Issue by iReadX** [johng-cn/gf#16]
文档代码：
```go
if tx, err := db.Begin(); err == nil {
    r, err := tx.Table("user").Data(gdb.Map{"uid":1, "name": "john_1"}).Save()
    tx.Commit()
    fmt.Println(r, err)
}
````

在使用过程中多进行一条语句操作，事务就不生效了：
```go
if tx, err := db.Begin(); err == nil {
    r, err := tx.Table("user").Data(gdb.Map{"uid":1, "name": "john_1"}).Save()
    rd, errd := tx.Table("user").Where("uid=?",2).Delete()
    tx.Commit()
    fmt.Println(r, err)
    fmt.Println(rd, errd)
}
````
文档中也没有找到相关的介绍，不知道这是框架的机制还是我使用不正确造成的，还望大神回复一下。

**Comment by johng-cn** [comment]
@iReadX 既然你提了，于是我就测试了一下，并不存在你说的情况，测试代码如下：
```go
package main

import (
    "fmt"
    "gitee.com/johng/gf/g"
    "gitee.com/johng/gf/g/database/gdb"
)

func main() {
    db := g.DB()
    db.SetDebug(true)

    if tx, err := db.Begin(); err == nil {
        r, err   := tx.Table("user").Data(gdb.Map{"id": 1, "nickname": "john111"}).Save()
        rd, errd := tx.Table("user").Where("id=?", 2).Delete()
        tx.Commit()
        fmt.Println(r, err)
        fmt.Println(rd, errd)
    }
}
```
运行截图如下：
1. 已有数据截图
<img width="523" alt="default" src="https://user-images.githubusercontent.com/26347176/50198557-1a67f680-0387-11e9-8578-27db0bb11df7.png">

1. 运行过程如图
<img width="1388" alt="default" src="https://user-images.githubusercontent.com/26347176/50198582-26ec4f00-0387-11e9-8f30-ebe7e860499a.png">

1. 运行结果如下
<img width="619" alt="default" src="https://user-images.githubusercontent.com/26347176/50198595-35d30180-0387-11e9-9f61-d136a3ac02b1.png">
