### ISSUE TITLE
性能如何？和主流web框架来个benchmark比一下？

### ISSUE THREAD

**Issue by mogenyun** [johng-cn/gf#5]
首先支持一下。
性能如何？和主流web框架来个benchmark比一下？

**Comment by johng-cn** [comment]
感谢支持。
之前有朋友做过测试说性能和tango框架差不多(不知道怎么测的)，回头我综合做一个测试结果列表出来，因为除了底层的http包，其他组件全是原创开发的，我对里面的细节最清楚，框架自身逻辑比较简单，性能应该是很高的。

**Comment by johng-cn** [comment]
你好，测试结果请参看以下地址：
[http://gf.johng.cn/637443](http://gf.johng.cn/637443)

**Comment by mogenyun** [comment]
@johng-cn 为你的执行力点赞
