### ISSUE TITLE
数据库查询结果集转Time类型错误，请问查询出来的时间类型能转time.Time么？

### ISSUE THREAD

**Issue by go-xworkflow** [johng-cn/gf#7]
数据库查询结果集转Time类型错误，请问查询出来的时间类型能转time.Time么？
我看到Value有个Time方法呀
难道要数据库里的是整型才行？

**Comment by johng-cn** [comment]
你好，之前版本只支持整型转Time类型，新版本已增加了对DATE字段类型的支持，请更新后使用。

**Comment by go-xworkflow** [comment]
@johng-cn 你好，我update了你最新的代码，使用的是postgresql数据库，时间字段的数据库类型是timestamp，数据库查询结果集转Time类型还是错误，我看了你最新的源代码，应该是时间类型的模板有问题，我将这个类型的字段转String，都是类似这样的数据，“2018-02-09T20:33:18.814Z“，”2018-02-09T20:46:17.897Z”，请将此功能在做一下完整的测试，另外是否所有数据库都能支持？
