### ISSUE TITLE
关于数据查询结果集转Time类型错误

### ISSUE THREAD

**Issue by go-xworkflow** [johng-cn/gf#8]
@johng-cn 你好，我update了你最新的代码，使用的是postgresql数据库，时间字段的数据库类型是timestamp，数据库查询结果集转Time类型还是错误，我看了你最新的源代码，应该是时间类型的模板以及正则的使用有问题、我将我的这个时间类型的字段转String，都是类似这样的数据，“2018-02-09T20:33:18.814Z“，”2018-02-09T20:46:17.897Z”，另外该功能是否所有数据库都能支持，请将此功能在做一下完整的测试，谢谢。

**Comment by johng-cn** [comment]
你好，问题收到，目前只是在MySQL的时间日期类型上测试通过，没有测试PostgreSQL，看了你发的数据值，目前对ISODate类型还不支持，我今天会把支持加上去。

**Comment by johng-cn** [comment]
已改进，请更新最新版本代码后重试。
